server:
  port: 8084
spring:
  application:
    name: ly-goods
  rabbitmq:
    host: 127.0.0.1
    username: root
    password: 123
    virtual-host: /leyou
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/yun6?useUnicode=true&characterEncoding=utf8&useSSL=true&serverTimezone=UTC&allowMultiQueries=true
    username: root
    password: 123
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}